### ISSUE TITLE
这个博客的样式可以改进吗？

### ISSUE THREAD

**Issue by Archsx** [aprilandjan/aprilandjan.github.io#2]
很喜欢您的文章 但是没有一个归类(目录) 只能上一页 下一页的查看 不太方便查阅。

**Comment by aprilandjan** [comment]
@Archsx 感谢关注！

该博客使用的主题比较简洁，没有目录页，见谅，有空的话会考虑使用其他的静态站点生成方案替换到该模版。

**Comment by Archsx** [comment]
我知道了！只需要clone这个项目，在_post文件夹里面就可以看到所有文章了！
